# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Get current version
      id: get_version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Current version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_ENV

    - name: Increment patch version
      id: increment_version
      run: |
        CURRENT_VERSION=${{ env.version }}
        IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT_VERSION"
        PATCH_VERSION=${VERSION_PARTS[2]//[!0-9]/}
        NEW_PATCH_VERSION=$((PATCH_VERSION + 1))
        NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$NEW_PATCH_VERSION"
        echo "New version: $NEW_VERSION"
        mvn versions:set -DnewVersion=$NEW_VERSION
        echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Commit and push updated version
      if: github.ref == 'refs/heads/master'
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git commit -am "Bump version to ${{ env.new_version }}"
        git tag -a "v${{ env.new_version }}" -m "Version ${{ env.new_version }}"
        git push origin master --tags

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
